const petsList = [
  {
    id: 1,
    type: "Dog",
    name: "Bradley",
    status: "Adopted",
    picture: "pic",
    height: 14,
    weight: 75,
    color: "White/Blue",
    bio: "",
    hypoallergnic: false,
    dietery: [],
    breed: "Pit Bull Mix",
  },
  {
    id: 2,
    type: "Cat",
    name: "Rajah",
    status: "Adopted",
    picture: "pic",
    height: 4,
    weight: 65,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    id: 3,
    type: "Cat",
    name: "Pebbles",
    status: "Adopted",
    picture: "pic",
    height: 84,
    weight: 75,
    color: "Calico",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    id: 4,
    type: "Dog",
    name: "Johnny",
    status: "Adopted",
    picture: "pic",
    height: 66,
    weight: 88,
    color: "Blue/White",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Pit Bull",
  },
  {
    id: 5,
    type: "Cat",
    name: "Miso",
    status: "Adopted",
    picture: "pic",
    height: 26,
    weight: 8,
    color: "Brown Tabby/White",
    bio: "",
    hypoallergnic: false,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    id: 6,
    type: "Cat",
    name: "Lucky Charm",
    status: "Adopted",
    picture: "pic",
    height: 10,
    weight: 69,
    color: "Orange Tabby",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    id: 7,
    type: "Dog",
    name: "Megatron",
    status: "Adopted",
    picture: "pic",
    height: 44,
    weight: 14,
    color: "Red",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Dachshund/Chihuahua Shorthair",
  },
  {
    id: 8,
    type: "Dog",
    name: "Moomoo",
    status: "Adopted",
    picture: "pic",
    height: 98,
    weight: 96,
    color: "White/Black",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "French Bulldog/Pit Bull",
  },
  {
    id: 9,
    type: "Dog",
    name: "Lindi",
    status: "Adopted",
    picture: "pic",
    height: 94,
    weight: 67,
    color: "Black/White",
    bio: "",
    hypoallergnic: false,
    dietery: [],
    breed: "Pit Bull Mix",
  },
  {
    id: 10,
    type: "Dog",
    name: "Church",
    status: "Adopted",
    picture: "pic",
    height: 97,
    weight: 17,
    color: "Brown Brindle",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Plott Hound Mix",
  },
  {
    id: 11,
    type: "Cat",
    name: "Huncho",
    status: "Adopted",
    picture: "pic",
    height: 85,
    weight: 47,
    color: "White/Brown Tabby",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    id: 12,
    type: "Dog",
    name: "Calvin",
    status: "Adopted",
    picture: "pic",
    height: 40,
    weight: 90,
    color: "Tan/White",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Border Terrier Mix",
  },
  {
    id: 13,
    type: "Cat",
    name: "Sandi",
    status: "Adopted",
    picture: "pic",
    height: 52,
    weight: 39,
    color: "Torbie/White",
    bio: "",
    hypoallergnic: false,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
];

const searchParam = {
  type: "Dog",
  name: "",
  height: {min: 10, max: 100},
  weight: {min: 10, max: 100},
  status: ["Adopted", "Fostered", "Available"],
};
const keys = ["type", "name", "height", "weight", "status"];

// console.log(searchParam.status.forEach((item) => console.log(item)));

const search = (database) => {
  return database.filter((obj) =>
    keys.some((key) => {
      return obj[key];
    })
  );
};

console.log(search(petsList));
// .toString().includes(searchParam)